schema_version: 1

context:
  name: module-qc-database-tools
  version: "2.7.2"
  python_min: '3.9'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/module_qc_database_tools-${{ version }}.tar.gz
  sha256: c0eda8cd31192f7cb5461e1dbe270562fb17fe445b8268e40029716ea1078910

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - module-qc-database-tools = module_qc_database_tools.cli:app
      - mqdbt = module_qc_database_tools.cli:app
      - influxdbtool-retrieve = module_qc_database_tools.cli.influxdbtool_retrieve:main
      - localdbtool-retrieve = module_qc_database_tools.cli.localdbtool_retrieve:main
      - localdbtool-upload = module_qc_database_tools.cli.localdbtool_upload:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling >=0.7
    - hatch-vcs
  run:
    - python >=${{ python_min }}
    - itkdb >=0.6.14
    - pandas
    - pyarrow
    - typer
    - pymongo >=4.0.0
    - jsondiff
    - jsbeautifier
    - rich
    - urllib3 >=1.26.20
    - itksn >=0.4.2
    - influxdb
    - cachecontrol <=0.14.1
    - arrow
    - packaging
    # Actually only required for [py<310] but require for all Python versions so this can be noarch: python
    - typing_extensions >=4.0
    - module-qc-data-tools >=1.3.1
    - typing_extensions >=4.0

tests:
  - python:
      imports:
        - module_qc_database_tools
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - mqdbt --help
      - mqdbt --version
      - influxdbtool-retrieve --help
      - localdbtool-retrieve --help
      - localdbtool-upload --help

about:
  summary: Python wrapper to interface with LocalDB and Production DB for common tasks for pixel modules.
  homepage: https://gitlab.cern.ch/atlas-itk/pixel/module/module-qc-database-tools
  repository: https://gitlab.cern.ch/atlas-itk/pixel/module/module-qc-database-tools
  documentation: https://atlas-itk-pixel-mqdbt.docs.cern.ch/latest/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kratsg
    - elisabettapianori
    - marijamarjanovic
    - lime86
